nameOverride: ""
fullnameOverride: ""

webFrontend:
  replicaCount: 1

  image:
    repository: nginx
    tag: "1.27"
    pullPolicy: IfNotPresent

  service:
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 31263

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi


orderProcessor:
  replicaCount: 1

  image:
    repository: python
    tag: "3.12-slim"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi


paymentGateway:
  replicaCount: 1

  image:
    repository: alpine
    tag: "3.20"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
