apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-processor
  template:
    metadata:
      labels:
        app: order-processor
    spec:
      containers:
        - name: order-processor
          image: nginx:latest
          ports:
            - containerPort: 80
