apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1m

  secretStoreRef:
    name: mock-secret-store
    kind: SecretStore

  target:
    name: db-secret
    creationPolicy: Owner

  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: mock-external-secret
        property: DB_PASSWORD
