apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
    {{- include "payments.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc | quote }}
