apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
  labels:
    {{- include "payments.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.webFrontend.replicaCount }}
  selector:
    matchLabels:
      app: web-frontend
  template:
    metadata:
      labels:
        app: web-frontend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101

      containers:
        - name: web-frontend
          image: "{{ .Values.webFrontend.image.repository }}:{{ .Values.webFrontend.image.tag }}"
          imagePullPolicy: {{ .Values.webFrontend.image.pullPolicy }}

          ports:
            - name: http
              containerPort: 80
              protocol: TCP

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          resources:
            {{- toYaml .Values.webFrontend.resources | nindent 12 }}

          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx

            - name: nginx-run
              mountPath: /var/run

            - name: nginx-tmp
              mountPath: /tmp

      volumes:
        - name: nginx-cache
          emptyDir: {}

        - name: nginx-run
          emptyDir: {}

        - name: nginx-tmp
          emptyDir: {}
